# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        
#    - name: Tag Version
#      run: export REPLICADB_RELEASE_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec) && echo ${REPLICADB_RELEASE_VERSION}
 
    - name: Build with Maven
      run: mvn -DskipTests -B package --file pom.xml
        

    - name: Clean Install
      run: |
        export REPLICADB_RELEASE_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec) 
        echo ${REPLICADB_RELEASE_VERSION}  
        mvn clean install -Dmaven.javadoc.skip=true -DskipTests -B -V -P release 
        cp ./target/ReplicaDB-*.jar . 
        mkdir lib
        echo ${REPLICADB_RELEASE_VERSION} 
        cp ./target/lib/* ./lib 
        tar -zcvf ReplicaDB-v${REPLICADB_RELEASE_VERSION}.tar.gz ReplicaDB-*.jar README.md lib conf bin LICENSE 
        zip -r -X ReplicaDB-v${REPLICADB_RELEASE_VERSION}.zip ReplicaDB-*.jar README.md lib conf bin LICENSE 
        ls -lahtr
        gh auth login --with-token < uTsJSmremnkRffvTxwaktVWQ6TShFN9kevhZM147jKF87/2HhUhxPO0qoGDRnALf/I3cUGVTDFA8TtpkSXC3sHChf4x/8t/wXxShSAUJbP1HdrC803s+BzA5lBwq8obiWWFTMwoceDJBYlC5ofisJwjIN0wR2h0pa5gOhU35sqo9dOdmEBE8QPIPYCPxKf3UFJZVNX7ewy57Ag3JYTTlYsV6qYhkBw0Z0Pb0SiaKH3pySYLl4r8KsA35mqlMW3U2vVhWSovGiP6amF9GBePUPRcVpAbdqq5tl7PIRqmLD6uPe93MDZ0jl5gtupNyAPWGHaeNj2ydXO5qpgkgk8mFJzafjAv0IbhVJMg95Dtch/abK8xWKxlFbcX1D8b7j507Bc1i9IA8YAEr3nj2bRq86AgS7yLQu3of5/o36ZPacOwRqVNbkoiswvHj/x4OuQ5C3ywUe/qrRmkDkEuw06G2tYl5XRNg8/TRkLMxcyUTfTJ1Yq2S4sp8EG5h5GEyF7yw5OkuD4eOaW4uvyB2wwfPULmGHwOfNSfzrwqW2qi/zKzt2tARn7r6uWn07OvlDbdbGKAa+pOInlwLmHLNXKR0c7Po629fLVntj7MktNXzB5pRGneojpQtS+pSiGhnmBEeQtWqPpolzVx9ojuwUddPwiVMuPEow8DqrE1x1sPv5Og=
        gh release create v${REPLICADB_RELEASE_VERSION} ./ReplicaDB-v*  -t "Release v${REPLICADB_RELEASE_VERSION}"
        
        
  
    #- name: Get version
    #  run: echo "version=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec) " >> $GITHUB_ENV
    

