# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        
    - name: Tag Version
      run: export REPLICADB_RELEASE_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec) && echo ${REPLICADB_RELEASE_VERSION}
 
    - name: Build with Maven
      run: mvn -DskipTests -B package --file pom.xml
        

    - name: Clean Install
      run: mvn clean install -Dmaven.javadoc.skip=true -DskipTests -B -V -P release && cp ./target/ReplicaDB-*.jar . && mkdir lib && echo echo ${REPLICADB_RELEASE_VERSION} && cp ./target/lib/* ./lib && tar -zcvf ReplicaDB-${REPLICADB_RELEASE_VERSION}.tar.gz ReplicaDB-*.jar README.md lib conf bin LICENSE && zip -r -X ReplicaDB-${REPLICADB_RELEASE_VERSION}.zip ReplicaDB-*.jar README.md lib conf bin LICENSE 

    - name: LS
      run: ls -lahtr
